# Generated by Django 5.2.17 on 2026-08-06 11:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consultation_date', models.DateField()),
                ('report_type', models.CharField(choices=[('consultation', 'Consultation'), ('epicrisis', 'Epicrisis'), ('follow_up', 'Follow-up'), ('discharge', 'Discharge Summary')], default='consultation', max_length=20)),
                ('subjective', models.TextField(blank=True, default='')),
                ('objective', models.TextField(blank=True, default='')),
                ('assessment', models.TextField(blank=True, default='')),
                ('plan', models.TextField(blank=True, default='')),
                ('raw_transcript', models.TextField(blank=True, default='')),
                ('transcript_segments', models.JSONField(blank=True, default=list)),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='reports/excel/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='patients.patient')),
            ],
            options={
                'ordering': ['-consultation_date', '-created_at'],
                'indexes': [models.Index(fields=['patient', 'consultation_date'], name='reports_med_patient_890b20_idx'), models.Index(fields=['doctor', 'consultation_date'], name='reports_med_doctor__31276d_idx'), models.Index(fields=['report_type'], name='reports_med_report__219d7f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio_file', models.FileField(upload_to='audio/%Y/%m/%d/')),
                ('transcript', models.TextField()),
                ('language', models.CharField(blank=True, default='', max_length=10)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('segments', models.JSONField(blank=True, default=list)),
                ('model_used', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'created_at'], name='reports_tra_patient_47f4fd_idx'), models.Index(fields=['doctor', 'created_at'], name='reports_tra_doctor__ae735c_idx')],
            },
        ),
    ]
